name: Generate and Upload Wallpapers to Subreddit

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '30 4 * * 5'  # Run every Friday at 10:00 AM IST (IST is UTC+5:30, cron is in UTC)

jobs:
  generate-and-upload-wallpapers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Change this to the version you need

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Plex Wallpaper Generation Script
        run: |
          python plex.py
        env:
          PLEX_BASEURL: ${{ secrets.PLEX_BASEURL }}
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}

      - name: Run TMDB Wallpaper Generation Script
        run: |
          python TMDBlogo.py
        env:
          TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}

      - name: Upload Wallpapers to Subreddit
        run: |
          python upload_wallpaper.py
        env:
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          SUBREDDIT: ${{ secrets.REDDIT_SUBREDDIT }}

      - name: Commit and Push Metadata Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add uploaded_wallpapers.txt  # Only add the metadata file
          git commit -m "Update metadata file to track uploaded images" || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
